#!/usr/bin/bash

# Add submodules folder to the list of folders that Python searches for imported modules
export PYTHONPATH="$PYTHONPATH:$MISYSTEM_PROJECT_DIR/submodules"

# Running the main python file
$MISYSTEM_PROJECT_DIR/main.py
